use super::super::*;

pub(crate) const CULL_MAP_FILE: &str = "cull.map";
pub(crate) const CULL_CLIENT_FILE: &str = "eagle_cull.lua";

pub(crate) fn cull_map_path(root: &Path) -> PathBuf {
    root.join(CULL_MAP_FILE)
}

pub(crate) fn cull_map_path_for_source(root: &Path, source: LoadSceneSource) -> PathBuf {
    match source {
        LoadSceneSource::Autosave => autosave_root_path(root).join(CULL_MAP_FILE),
        LoadSceneSource::Saved if wip_root_path(root).join(CULL_MAP_FILE).is_file() => {
            wip_root_path(root).join(CULL_MAP_FILE)
        }
        _ => cull_map_path(root),
    }
}

pub(crate) fn load_cull_zones_for_source(root: &Path, source: LoadSceneSource) -> Vec<CullZone> {
    load_cull_zones(&cull_map_path_for_source(root, source))
}

pub(crate) fn load_cull_zones(path: &Path) -> Vec<CullZone> {
    let Ok(text) = fs::read_to_string(path) else {
        return Vec::new();
    };
    let tag_re = Regex::new(r#"(?i)<cull\s+([^>]*)/?>"#).unwrap();
    let attr_re = Regex::new(r#"([A-Za-z_][A-Za-z0-9_]*)=\"([^\"]*)\""#).unwrap();
    tag_re
        .captures_iter(&text)
        .filter_map(|capture| {
            let attrs = parse_attrs(&capture[1], &attr_re);
            if !attrs
                .get("type")
                .is_none_or(|value| value.eq_ignore_ascii_case("water"))
            {
                return None;
            }
            let center = V3 {
                x: attrf(&attrs, "posX"),
                y: attrf(&attrs, "posY"),
                z: attrf(&attrs, "posZ"),
            };
            let size = V3 {
                x: attrf(&attrs, "sizeX").abs(),
                y: attrf(&attrs, "sizeY").abs(),
                z: attrf(&attrs, "sizeZ").abs(),
            };
            (size.x > 0.0 && size.y > 0.0 && size.z > 0.0).then(|| CullZone {
                id: attrs
                    .get("id")
                    .cloned()
                    .unwrap_or_else(|| "water_cull".to_string()),
                center,
                size,
            })
        })
        .collect()
}

fn xml(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

pub(crate) fn cull_map_text(zones: &[CullZone]) -> String {
    let mut out = String::from(
        "<map>\n    <info name=\"Eagle water cull zones\" author=\"Eagle Editor\" version=\"1.0\"></info>\n",
    );
    for zone in zones {
        out.push_str(&format!(
            "    <cull id=\"{}\" type=\"water\" posX=\"{:.3}\" posY=\"{:.3}\" posZ=\"{:.3}\" sizeX=\"{:.3}\" sizeY=\"{:.3}\" sizeZ=\"{:.3}\" />\n",
            xml(&zone.id), zone.center.x, zone.center.y, zone.center.z,
            zone.size.x.max(0.1), zone.size.y.max(0.1), zone.size.z.max(0.1)
        ));
    }
    out.push_str("</map>\n");
    out
}

const CULL_CLIENT_LUA: &str = r#"-- Generated by Eagle Editor. Water cull zones are authored in cull.map.
local CULL_MAP = "cull.map"
local HIDDEN_WATER_DIMENSION = 65535
local zones, originalDimensions = {}, {}
local waterHidden = false

local function loadZones()
    local xml = xmlLoadFile(CULL_MAP)
    if not xml then return end
    for _, node in ipairs(xmlNodeGetChildren(xml)) do
        if xmlNodeGetName(node) == "cull" then
            local a = xmlNodeGetAttributes(node)
            if not a.type or a.type:lower() == "water" then
                local sx, sy, sz = math.abs(tonumber(a.sizeX) or 0), math.abs(tonumber(a.sizeY) or 0), math.abs(tonumber(a.sizeZ) or 0)
                if sx > 0 and sy > 0 and sz > 0 then
                    zones[#zones + 1] = { x = tonumber(a.posX) or 0, y = tonumber(a.posY) or 0, z = tonumber(a.posZ) or 0, hx = sx / 2, hy = sy / 2, hz = sz / 2 }
                end
            end
        end
    end
    xmlUnloadFile(xml)
end

local function insideWaterCull()
    local x, y, z = getElementPosition(localPlayer)
    for _, zone in ipairs(zones) do
        if math.abs(x - zone.x) <= zone.hx and math.abs(y - zone.y) <= zone.hy and math.abs(z - zone.z) <= zone.hz then return true end
    end
    return false
end

local function hideWater(water)
    if not isElement(water) then return end
    if originalDimensions[water] == nil then originalDimensions[water] = getElementDimension(water) or 0 end
    setElementDimension(water, HIDDEN_WATER_DIMENSION)
end

local function hideAllWater()
    for _, water in ipairs(getElementsByType("water")) do hideWater(water) end
    waterHidden = true
end

local function restoreAllWater()
    for water, dimension in pairs(originalDimensions) do if isElement(water) then setElementDimension(water, dimension) end end
    originalDimensions, waterHidden = {}, false
end

local function syncWater()
    local inside = insideWaterCull()
    if inside and not waterHidden then hideAllWater() elseif not inside and waterHidden then restoreAllWater() end
end

addEventHandler("onClientElementCreate", root, function() if waterHidden and getElementType(source) == "water" then hideWater(source) end end)
addEventHandler("onClientResourceStop", resourceRoot, function() if waterHidden then restoreAllWater() end end)
addEventHandler("onClientResourceStart", resourceRoot, function() loadZones(); syncWater(); setTimer(syncWater, 250, 0) end)
"#;

fn ensure_meta_entry(root: &Path, entry: &str, needle: &str) -> Result<(), String> {
    let path = root.join("meta.xml");
    let mut text = fs::read_to_string(&path).unwrap_or_else(|_| "<meta>\n</meta>\n".to_string());
    if text.contains(needle) {
        return Ok(());
    }
    let at = text
        .rfind("</meta>")
        .ok_or_else(|| "meta.xml has no </meta> tag".to_string())?;
    text.insert_str(at, entry);
    fs::write(&path, text).map_err(|err| format!("{}: {err}", path.display()))
}

pub(crate) fn save_cull_system(
    root: &Path,
    zones: &[CullZone],
    patch_meta: bool,
) -> Result<(), String> {
    if zones.is_empty() && !root.join(CULL_MAP_FILE).is_file() {
        return Ok(());
    }
    fs::create_dir_all(root).map_err(|err| format!("{}: {err}", root.display()))?;
    fs::write(root.join(CULL_MAP_FILE), cull_map_text(zones)).map_err(|err| err.to_string())?;
    if patch_meta {
        fs::write(root.join(CULL_CLIENT_FILE), CULL_CLIENT_LUA).map_err(|err| err.to_string())?;
        ensure_meta_entry(
            root,
            "    <file src=\"cull.map\" type=\"client\" />\n",
            "src=\"cull.map\"",
        )?;
        ensure_meta_entry(
            root,
            "    <script src=\"eagle_cull.lua\" type=\"client\" />\n",
            "src=\"eagle_cull.lua\"",
        )?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn cull_map_round_trip() {
        let dir = std::env::temp_dir().join(format!("eagle-cull-{}", std::process::id()));
        let zones = vec![CullZone {
            id: "water & tunnel".into(),
            center: V3 {
                x: 1.0,
                y: 2.0,
                z: -3.0,
            },
            size: V3 {
                x: 10.0,
                y: 20.0,
                z: 30.0,
            },
        }];
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join(CULL_MAP_FILE), cull_map_text(&zones)).unwrap();
        assert_eq!(load_cull_zones(&dir.join(CULL_MAP_FILE)), zones);
        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn saving_cull_system_installs_runtime_and_meta_entries() {
        let dir = std::env::temp_dir().join(format!("eagle-cull-save-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("meta.xml"), "<meta>\n</meta>\n").unwrap();
        let zones = vec![CullZone {
            id: "water_cull_001".into(),
            center: V3::default(),
            size: V3 {
                x: 4.0,
                y: 6.0,
                z: 8.0,
            },
        }];

        save_cull_system(&dir, &zones, true).unwrap();

        let meta = fs::read_to_string(dir.join("meta.xml")).unwrap();
        assert!(meta.contains("src=\"cull.map\""));
        assert!(meta.contains("src=\"eagle_cull.lua\""));
        let lua = fs::read_to_string(dir.join(CULL_CLIENT_FILE)).unwrap();
        assert!(lua.contains("setElementDimension(water, HIDDEN_WATER_DIMENSION)"));
        assert!(lua.contains("setElementDimension(water, dimension)"));
        let _ = fs::remove_dir_all(dir);
    }
}
